### ISSUE TITLE
Incomplete credit-card numbers get validated as valid

### ISSUE THREAD

**Issue by bbuhler** [Adyen/CSE-JS#6]
Why are the following incomplete credit-card numbers validated true?

``` javascript
cseInstance.validate({ number: '499897' });
// returns: { valid=true,  number=true,  luhn=true}

cseInstance.validate({ number: '41111' });
// returns: { valid=true,  number=true,  luhn=true}
```

According to http://www.validcreditcardnumber.com/ they aren't valid.

**Comment by ArnoudAdyen** [comment]
Hi, 

The current validation only includes a Luhn validation, and no length checks because currently the primary goal of the validation is to catch people mistyping their credit card number rather than prevent people typing in random length numbers (which will be rejected  by the authorisation API).

The provided numbers are valid according to the Luhn validations, but I agree that it is not to much work to apply a minimal length check as well. I will schedule to include it, but this will need to do a slight bit of research as card numbers can vary in length and we don't want to introduce false negatives.

An update is planned already end of this week, maybe early next week. Let's see if I can push a change on this validation behavior as well, to at least include a 10~13 character minimum (pending research).

Kind regards,

Arnoud

**Comment by ArnoudAdyen** [comment]
This was fixed in 0_1_15 release. So let's close this issue.
