### ISSUE TITLE
Remove log statements in addons/adyen.cardtype.js

### ISSUE THREAD

**Issue by oyvindberg** [Adyen/CSE-JS#63]
We use this part of the library to identify card types, and the logspam caused by `console.log` inside there is an irritation. Can we please take them out?

**Comment by ArnoudAdyen** [comment]
Yes. Makes sense. Will do this in the next iteration.

**Comment by lauterry** [comment]
Hi

Are you talking about thoses logs ?

![capture d ecran 2018-02-05 a 17 03 28](https://user-images.githubusercontent.com/1374238/35814529-8b3ac382-0a96-11e8-9350-24d3226a34f5.jpg)

Yes it should be removed as soon as possible since it appears in production.

Any updates about when it will be shipped ?

Best regards

**Comment by lauterry** [comment]
Hi

Any updates about when it will be shipped ?

Best regards

**Comment by lauterry** [comment]
Hi 

Any updates about when it will be shipped ?

Best regards

**Comment by lauterry** [comment]
Hi

Any updates about when it will be shipped ?

Best regards

**Comment by mastermatt** [comment]
@lauterry no one at Adyen monitors this repo. You have to contact (pester) your rep to get any kind of feedback on this library, which [may or may not be deprecated](https://www.npmjs.com/package/adyen-cse-web).
