### ISSUE TITLE
Is Device finger printing included/exposed in this library?

### ISSUE THREAD

**Issue by catalinfeier** [Adyen/CSE-JS#64]
The version history mentions `Add device fingerprinting as part of fraud detection`. Is this functionality exposed in any way to be used for [device fingerprinting](https://docs.adyen.com/developers/risk-management/device-fingerprinting) ?

**Comment by severin** [comment]
It seems that the code is included (see https://github.com/Adyen/adyen-cse-web/blob/master/js/adyen.encrypt.js#L202-L204) but the functionality is not exposed/usable.

@adyen-git-manager please make the `df` functions or the calculated fingerprint available so that we do not have to load the df code twice...
