### ISSUE TITLE
Expiration date with two digits

### ISSUE THREAD

**Issue by greeven** [Adyen/CSE-JS#75]
Ist there a way to implement with two digits for the expiration date instead of all four?

The only way I found so far is to make changes in the repository files themselves.

**Comment by chaltec** [comment]
Why am I getting this email?

I thought because I subscribed to it but I don’t have an account registered with that email adress.

Best,
Christian

Von: greeven [mailto:notifications@github.com]
Gesendet: Mittwoch, 23. Mai 2018 16:39
An: Adyen/adyen-cse-web <adyen-cse-web@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Adyen/adyen-cse-web] Expiration date with two digits (#75)


Ist there a way to implement with two digits for the expiration date instead of all four?

The only way I found so far is to make changes in the repository files themselves.
