### ISSUE TITLE
adyen-cse-web is not added to package-lock.json on `npm install`

### ISSUE THREAD

**Issue by fetimo** [Adyen/CSE-JS#78]
This means that it isn't found when running `npm ci` in a build process, causing it to fail.

**Steps to reproduce**

1. `npm install`
2. `npm ci`

The terminal outputs:
`npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with npm install before continuing.`
`npm ERR! Missing: adyen-cse-web@git+https://github.com/Adyen/adyen-cse-web.git#0_1_23`

**Versions**
npm 6.4.1
node 10.13.0
adyen-cse-web 0.1.23

**Comment by mastermatt** [comment]
While I do wish Adyen would publish this library to npm, @fetimo your issue is unrelated to anything Adyen has any control over. 

I just ran `npm install git+https://github.com/Adyen/adyen-cse-web.git#0_1_23` using npm 6.4.1 and it did indeed add the lib to package-lock.json as expected. Some miss step must have happened on your machine when adding the dependency.
When in doubt, you can always run `rm package-lock.json && npm i` to regenerate your lock file.
